services:
  gateway:
    command: "ipsec start --nofork"
    build:
      dockerfile: ./docker/gateway/Dockerfile
      context: .
      args:
        python_version: "${DOCKER_PYTHON_VERSION:?}"
    privileged: true

  roadwarrior:
    extends: gateway
    build:
      dockerfile: ./docker/roadwarrior/Dockerfile
      args:
        python_version: "${DOCKER_PYTHON_VERSION:?}"
    links:
     - "gateway"
